name: 'Update Image Tag'
description: 'Auto-update image tag in manifests repository based on images pushed on Amazon ECR'
inputs:
  repo_url:
    required: true
  github_user:
    default: "cicd"
  github_mail:
    default: "cicd@default.com"
  github_password:
    required: true
  app_name:
    required: true
  version:
    required: true
  release_tag:
    required: true
  cluster_directory:
    default: './eks-clusters'
runs:
  using: "composite"
  steps:
    - name: 'Prepare Environment'
      run: | 
          wget https://github.com/mikefarah/yq/releases/download/v4.30.1/yq_linux_amd64 -O /usr/bin/yq
          chmod +x /usr/bin/yq

          # Install GH
          wget https://github.com/cli/cli/releases/download/v2.20.2/gh_2.20.2_linux_amd64.deb -O gh.deb
          dpkg -i gh.deb
      shell: bash
    - name: 'Update Repository'
      env:
        GIT_USER: "${{ inputs.github_user }}"
        GIT_MAIL: "${{ inputs.github_mail }}"
        GH_TOKEN: "${{ inputs.github_password }}"
      run: |
        bash ${{ github.action_path }}/update_image_tag.sh "${{ inputs.repo_url }}" \
          "${{ inputs.release_tag }}" "${{ inputs.app_name }}" "${{ inputs.version }}" "${{ inputs.cluster_directory }}"
      shell: bash


